apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greencode.fullname" . }}-data-pvc
  labels:
    app.kubernetes.io/name: {{ include "greencode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "20Gi" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}

