apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greencode.fullname" . }}-sa
  labels:
    app.kubernetes.io/name: {{ include "greencode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "greencode.fullname" . }}-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "greencode.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "greencode.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "greencode.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io

