name: GreenCode to SonarQube Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarqube:
    name: SonarQube & GreenCode Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install GreenCode Auditor
        run: |
          pip install -r requirements.txt

      - name: Run GreenCode Auditor (Generate SonarQube & SARIF Reports)
        run: |
          python -m app.main --path . --threshold 75 --sonar greencode-sonar.json --sarif greencode.sarif

      - name: SonarQube Scan with GreenCode External Issues
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.externalIssuesReportPaths=greencode-sonar.json
            -Dsonar.sarifReportPaths=greencode.sarif

